In [1]:
import pandas as pd
df=pd.read_csv("cleveland (1).csv",sep=",")
df

63  1  1.1  145  233  1.2  2  150  0  2.3  3  0.1    6  0.2
0    67  1    4  160  286    0  2  108  1  1.5  2  3.0  3.0    2
1    67  1    4  120  229    0  2  129  1  2.6  2  2.0  7.0    1
2    37  1    3  130  250    0  0  187  0  3.5  3  0.0  3.0    0
3    41  0    2  130  204    0  2  172  0  1.4  1  0.0  3.0    0
4    56  1    2  120  236    0  0  178  0  0.8  1  0.0  3.0    0
..   .. ..  ...  ...  ...  ... ..  ... ..  ... ..  ...  ...  ...
297  45  1    1  110  264    0  0  132  0  1.2  2  0.0  7.0    1
298  68  1    4  144  193    1  0  141  0  3.4  2  2.0  7.0    2
299  57  1    4  130  131    0  0  115  1  1.2  2  1.0  7.0    3
300  57  0    2  130  236    0  2  174  0  0.0  2  1.0  3.0    1
301  38  1    3  138  175    0  0  173  0  0.0  1  NaN  3.0    0

[302 rows x 14 columns]

In [2]:
df.columns = ['age', 'sex', 'cp', 'trestbps', 'chol',

              'fbs', 'restecg', 'thalach', 'exang', 

              'oldpeak', 'slope', 'ca', 'thal', 'target']
df


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     67    1   4       160   286    0        2      108      1      1.5   
1     67    1   4       120   229    0        2      129      1      2.6   
2     37    1   3       130   250    0        0      187      0      3.5   
3     41    0   2       130   204    0        2      172      0      1.4   
4     56    1   2       120   236    0        0      178      0      0.8   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
297   45    1   1       110   264    0        0      132      0      1.2   
298   68    1   4       144   193    1        0      141      0      3.4   
299   57    1   4       130   131    0        0      115      1      1.2   
300   57    0   2       130   236    0        2      174      0      0.0   
301   38    1   3       138   175    0        0      173      0      0.0   

     slope   ca  thal  target  
0        2  3.0   3.0       2  
1        2  2.0   7.0       1  
2        3  0.0   3.0       0  
3        1  0.0   3.0       0  
4        1  0.0   3.0       0  
..     ...  ...   ...     ...  
297      2  0.0   7.0       1  
298      2  2.0   7.0       2  
299      2  1.0   7.0       3  
300      2  1.0   3.0       1  
301      1  NaN   3.0       0  

[302 rows x 14 columns]

In [3]:
modifiedFlights = df.dropna()
modifiedFlights.isnull().sum()
df=df.dropna()
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     67    1   4       160   286    0        2      108      1      1.5   
1     67    1   4       120   229    0        2      129      1      2.6   
2     37    1   3       130   250    0        0      187      0      3.5   
3     41    0   2       130   204    0        2      172      0      1.4   
4     56    1   2       120   236    0        0      178      0      0.8   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
296   57    0   4       140   241    0        0      123      1      0.2   
297   45    1   1       110   264    0        0      132      0      1.2   
298   68    1   4       144   193    1        0      141      0      3.4   
299   57    1   4       130   131    0        0      115      1      1.2   
300   57    0   2       130   236    0        2      174      0      0.0   

     slope   ca  thal  target  
0        2  3.0   3.0       2  
1        2  2.0   7.0       1  
2        3  0.0   3.0       0  
3        1  0.0   3.0       0  
4        1  0.0   3.0       0  
..     ...  ...   ...     ...  
296      2  0.0   7.0       1  
297      2  0.0   7.0       1  
298      2  2.0   7.0       2  
299      2  1.0   7.0       3  
300      2  1.0   3.0       1  

[296 rows x 14 columns]

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score


import warnings
warnings.filterwarnings('ignore')

In [5]:
df['target'].replace([0],['0'],inplace=True)
df['target'].replace([1],['1'],inplace=True)
df['target'].replace([2],['1'],inplace=True)
df['target'].replace([3],['1'],inplace=True)
df['target'].replace([4],['1'],inplace=True)
df['sex'] = df.sex.map({0: 'female', 1: 'male'})
df['sex'] = df.sex.map({'female': 0, 'male': 1})
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     67    1   4       160   286    0        2      108      1      1.5   
1     67    1   4       120   229    0        2      129      1      2.6   
2     37    1   3       130   250    0        0      187      0      3.5   
3     41    0   2       130   204    0        2      172      0      1.4   
4     56    1   2       120   236    0        0      178      0      0.8   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
296   57    0   4       140   241    0        0      123      1      0.2   
297   45    1   1       110   264    0        0      132      0      1.2   
298   68    1   4       144   193    1        0      141      0      3.4   
299   57    1   4       130   131    0        0      115      1      1.2   
300   57    0   2       130   236    0        2      174      0      0.0   

     slope   ca  thal target  
0        2  3.0   3.0      1  
1        2  2.0   7.0      1  
2        3  0.0   3.0      0  
3        1  0.0   3.0      0  
4        1  0.0   3.0      0  
..     ...  ...   ...    ...  
296      2  0.0   7.0      1  
297      2  0.0   7.0      1  
298      2  2.0   7.0      1  
299      2  1.0   7.0      1  
300      2  1.0   3.0      1  

[296 rows x 14 columns]

In [6]:
del df['age']
del df['trestbps']
del df['chol']
del df['thalach']
df

sex  cp  fbs  restecg  exang  oldpeak  slope   ca  thal target
0      1   4    0        2      1      1.5      2  3.0   3.0      1
1      1   4    0        2      1      2.6      2  2.0   7.0      1
2      1   3    0        0      0      3.5      3  0.0   3.0      0
3      0   2    0        2      0      1.4      1  0.0   3.0      0
4      1   2    0        0      0      0.8      1  0.0   3.0      0
..   ...  ..  ...      ...    ...      ...    ...  ...   ...    ...
296    0   4    0        0      1      0.2      2  0.0   7.0      1
297    1   1    0        0      0      1.2      2  0.0   7.0      1
298    1   4    1        0      0      3.4      2  2.0   7.0      1
299    1   4    0        0      1      1.2      2  1.0   7.0      1
300    0   2    0        2      0      0.0      2  1.0   3.0      1

[296 rows x 10 columns]

In [7]:
# Prepare data for modeling

y = df.target
X = df.drop('target', axis=1)

# setting up testing and training sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=27)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((207, 9), (89, 9), (207,), (89,))

In [9]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
classifier = DecisionTreeClassifier()



criterion = [ 'gini', 'entropy']
max_depth = [1,3,5 , None]
splitter = [ 'best', 'random']

grid = GridSearchCV(estimator=classifier, cv=3, param_grid=dict(criterion=criterion,max_depth= max_depth,splitter=splitter))

grid.fit(X,y)

print("Best Score via GridSearch", grid.best_score_)
print("Best parameters via GridSearch", grid.best_params_)


#Predict values based on new parameters
y_pred_acc = grid.predict(X_test)
# New Model Evaluation metrics 
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score

print('Accuracy Score : '  + str(accuracy_score(y_test,y_pred_acc)))
print('Precision Score : ' + str(precision_score(y_test, y_pred_acc, pos_label='1')))
print('Recall Score : '    + str(recall_score(y_test,y_pred_acc, pos_label='1')))
print('F1 Score : '        + str(f1_score(y_test,y_pred_acc, pos_label='1')))

# SVR (Grid Search) Confusion matrix
from sklearn.metrics import confusion_matrix
conf = confusion_matrix(y_test, y_pred_acc)
print('Confusion Matrix : \n' + str(conf))


TP = conf[0,0]
FP = conf[0,1]
TN = conf[1,0]
FN = conf[1,1]

sensitivity = TP / float(FN + TP)

print(' sensitivity : \n' + str(sensitivity))

specificity = TN / (TN + FP)

print(' specificity : \n' + str(specificity))

Best Score via GridSearch 0.8074324324324325
Best parameters via GridSearch {'criterion': 'gini', 'max_depth': 3, 'splitter': 'best'}
Accuracy Score : 0.8651685393258427
Precision Score : 0.8809523809523809
Recall Score : 0.8409090909090909
F1 Score : 0.8604651162790699
Confusion Matrix : 
[[40  5]
 [ 7 37]]
 sensitivity : 
0.5194805194805194
 specificity : 
0.5833333333333334


In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
RF=RandomForestClassifier()

grid_values ={
    'max_depth': [4, 6, 8],        # -- set of values for C
    'min_samples_leaf': [2, 5, 7], # -- set of values for epsilon
    'n_estimators': [70, 90, 100]  # -- set of values for gamma
}

# set the GridSearchCV 
gs = GridSearchCV(
    estimator=RF, # --- Check SVR with rbf kernel only
    param_grid=grid_values,
    cv=5,               # --- set with Cross-validation=5, 
    scoring='accuracy', # --- Check all parameters for high accuracy
    n_jobs=-1)          # --- Parallel processing,i.e., 2= use only 2 CPU, -1= use all available CPU
# run gridsearch
gs = gs.fit(X_train, y_train)
print("Best parameters via GridSearch", gs.best_params_)
#Predict values based on new parameters
y_pred_acc = gs.predict(X_test)

# New Model Evaluation metrics 
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score

print('Accuracy Score : '  + str(accuracy_score(y_test,y_pred_acc)))
print('Precision Score : ' + str(precision_score(y_test, y_pred_acc, pos_label='1')))
print('Recall Score : '    + str(recall_score(y_test,y_pred_acc, pos_label='1')))
print('F1 Score : '        + str(f1_score(y_test,y_pred_acc, pos_label='1')))

# SVR (Grid Search) Confusion matrix
from sklearn.metrics import confusion_matrix

conf = confusion_matrix(y_test, y_pred_acc)
print('Confusion Matrix : \n' + str(conf))
TP = conf[0,0]
FP = conf[0,1]
TN = conf[1,0]
FN = conf[1,1]

sensitivity = TP / float(FN + TP)

print(' sensitivity : \n' + str(sensitivity))

specificity = TN / (TN + FP)

print(' specificity : \n' + str(specificity))

Best parameters via GridSearch {'max_depth': 4, 'min_samples_leaf': 5, 'n_estimators': 70}
Accuracy Score : 0.8314606741573034
Precision Score : 0.8536585365853658
Recall Score : 0.7954545454545454
F1 Score : 0.8235294117647058
Confusion Matrix : 
[[39  6]
 [ 9 35]]
 sensitivity : 
0.527027027027027
 specificity : 
0.6


In [11]:


from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

#define the model and parameters
knn = KNeighborsClassifier()

parameters = {'n_neighbors':[4,5,6,7],
              'leaf_size':[1,3,5],
              'algorithm':['auto', 'kd_tree'],
              'n_jobs':[-1]}

#Fit the model
grid = GridSearchCV(knn, param_grid=parameters)
grid.fit(X,y)



print("Best Score via GridSearch", grid.best_score_)
print("Best parameters via GridSearch", grid.best_params_)


#Predict values based on new parameters
y_pred_acc = grid.predict(X_test)
# New Model Evaluation metrics 
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score

print('Accuracy Score : '  + str(accuracy_score(y_test,y_pred_acc)))
print('Precision Score : ' + str(precision_score(y_test, y_pred_acc, pos_label='1')))
print('Recall Score : '    + str(recall_score(y_test,y_pred_acc, pos_label='1')))
print('F1 Score : '        + str(f1_score(y_test,y_pred_acc, pos_label='1')))

# SVR (Grid Search) Confusion matrix
from sklearn.metrics import confusion_matrix


conf = confusion_matrix(y_test, y_pred_acc)
print('Confusion Matrix : \n' + str(conf))
TP = conf[0,0]
FP = conf[0,1]
TN = conf[1,0]
FN = conf[1,1]

sensitivity = TP / float(FN + TP)

print(' sensitivity : \n' + str(sensitivity))

specificity = TN / (TN + FP)

print(' specificity : \n' + str(specificity))


Best Score via GridSearch 0.7972972972972973
Best parameters via GridSearch {'algorithm': 'auto', 'leaf_size': 1, 'n_jobs': -1, 'n_neighbors': 7}
Accuracy Score : 0.8314606741573034
Precision Score : 0.8717948717948718
Recall Score : 0.7727272727272727
F1 Score : 0.8192771084337349
Confusion Matrix : 
[[40  5]
 [10 34]]
 sensitivity : 
0.5405405405405406
 specificity : 
0.6666666666666666


In [12]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(max_iter=100)


from sklearn.model_selection import GridSearchCV

parameters = {
    'hidden_layer_sizes': [(50,50,50), (50,100,50), (100,)],
    'activation': ['tanh', 'relu'],
    'solver': ['sgd', 'adam'],
    'alpha': [0.0001, 0.05],
    'learning_rate': ['constant','adaptive'],
}



#Fit the model
grid = GridSearchCV(mlp, param_grid=parameters, n_jobs=-1, cv=3)
grid.fit(X,y)




print("Best Score via GridSearch", grid.best_score_)
print("Best parameters via GridSearch", grid.best_params_)


#Predict values based on new parameters
y_pred_acc = grid.predict(X_test)
# New Model Evaluation metrics 
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score

print('Accuracy Score : '  + str(accuracy_score(y_test,y_pred_acc)))
print('Precision Score : ' + str(precision_score(y_test, y_pred_acc, pos_label='1')))
print('Recall Score : '    + str(recall_score(y_test,y_pred_acc, pos_label='1')))
print('F1 Score : '        + str(f1_score(y_test,y_pred_acc, pos_label='1')))

# SVR (Grid Search) Confusion matrix
from sklearn.metrics import confusion_matrix


conf = confusion_matrix(y_test, y_pred_acc)
print('Confusion Matrix : \n' + str(conf))
TP = conf[0,0]
FP = conf[0,1]
TN = conf[1,0]
FN = conf[1,1]

sensitivity = TP / float(FN + TP)

print(' sensitivity : \n' + str(sensitivity))

specificity = TN / (TN + FP)

print(' specificity : \n' + str(specificity))

Best Score via GridSearch 0.8277027027027027
Best parameters via GridSearch {'activation': 'relu', 'alpha': 0.0001, 'hidden_layer_sizes': (50, 100, 50), 'learning_rate': 'adaptive', 'solver': 'adam'}
Accuracy Score : 0.9101123595505618
Precision Score : 0.9736842105263158
Recall Score : 0.8409090909090909
F1 Score : 0.9024390243902439
Confusion Matrix : 
[[44  1]
 [ 7 37]]
 sensitivity : 
0.5432098765432098
 specificity : 
0.875


In [18]:

from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.linear_model import LogisticRegression

from sklearn import metrics
from sklearn.model_selection import KFold
KFold
# prepare cross validation
kfold = KFold(n_splits=10, random_state=123, shuffle=True)

# enumerate splits on the features (X) set 
for train_indx, test_indx in kfold.split(X):    
    X_train = X.iloc[train_indx]                  # -- set of X_train from X-set
    X_test  = X.iloc[test_indx]                   # -- set of X_test from X-set
    y_train, y_test = y.iloc[train_indx], y.iloc[test_indx] # -- set of y_train, y_test from y-set
    
    # Apply these set as a regular process for any classifier to test
    clf = LogisticRegression().fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    
    # Model Evaluation metrics 
    print('Accuracy Score : '  + str(accuracy_score(y_test,y_pred)))
    print('Precision Score : ' + str(precision_score(y_test,y_pred, pos_label='1')))
    print('Recall Score : '    + str(recall_score(y_test,y_pred, pos_label='1')))
    print('F1 Score : '        + str(f1_score(y_test,y_pred, pos_label='1')))

    #Logistic Regression Classifier Confusion matrix
    print('Confusion Matrix : \n' + str(confusion_matrix(y_test,y_pred)))
    conf = confusion_matrix(y_test, y_pred)

TP = conf[0,0]
FP = conf[0,1]
TN = conf[1,0]
FN = conf[1,1]

sensitivity = TP / float(FN + TP)

print(' sensitivity : \n' + str(sensitivity))

specificity = TN / (TN + FP)

print(' specificity : \n' + str(specificity))

Accuracy Score : 0.8666666666666667
Precision Score : 0.875
Recall Score : 0.875
F1 Score : 0.875
Confusion Matrix : 
[[12  2]
 [ 2 14]]
Accuracy Score : 0.8666666666666667
Precision Score : 0.8666666666666667
Recall Score : 0.8666666666666667
F1 Score : 0.8666666666666667
Confusion Matrix : 
[[13  2]
 [ 2 13]]
Accuracy Score : 0.7
Precision Score : 0.8
Recall Score : 0.6666666666666666
F1 Score : 0.7272727272727272
Confusion Matrix : 
[[ 9  3]
 [ 6 12]]
Accuracy Score : 0.8666666666666667
Precision Score : 0.8571428571428571
Recall Score : 0.8571428571428571
F1 Score : 0.8571428571428571
Confusion Matrix : 
[[14  2]
 [ 2 12]]
Accuracy Score : 0.8333333333333334
Precision Score : 0.75
Recall Score : 0.6666666666666666
F1 Score : 0.7058823529411765
Confusion Matrix : 
[[19  2]
 [ 3  6]]
Accuracy Score : 0.8
Precision Score : 0.8421052631578947
Recall Score : 0.8421052631578947
F1 Score : 0.8421052631578947
Confusion Matrix : 
[[ 8  3]
 [ 3 16]]
Accuracy Score : 0.9310344827586207
Precis

In [20]:
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.naive_bayes import GaussianNB

from sklearn import metrics
from sklearn.model_selection import KFold
KFold
# prepare cross validation
kfold = KFold(n_splits=10, random_state=123, shuffle=True)

# enumerate splits on the features (X) set 
for train_indx, test_indx in kfold.split(X):    
    X_train = X.iloc[train_indx]                  # -- set of X_train from X-set
    X_test  = X.iloc[test_indx]                   # -- set of X_test from X-set
    y_train, y_test = y.iloc[train_indx], y.iloc[test_indx] # -- set of y_train, y_test from y-set
    
    # Apply these set as a regular process for any classifier to test
    clf = GaussianNB().fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    
    # Model Evaluation metrics 
    print('Accuracy Score : '  + str(accuracy_score(y_test,y_pred)))
    print('Precision Score : ' + str(precision_score(y_test,y_pred, pos_label='1')))
    print('Recall Score : '    + str(recall_score(y_test,y_pred, pos_label='1')))
    print('F1 Score : '        + str(f1_score(y_test,y_pred, pos_label='1')))

    #Logistic Regression Classifier Confusion matrix
    print('Confusion Matrix : \n' + str(confusion_matrix(y_test,y_pred)))

    conf = confusion_matrix(y_test, y_pred)

TP = conf[0,0]
FP = conf[0,1]
TN = conf[1,0]
FN = conf[1,1]

sensitivity = TP / float(FN + TP)

print(' sensitivity : \n' + str(sensitivity))

specificity = TN / (TN + FP)

print(' specificity : \n' + str(specificity))

Accuracy Score : 0.9
Precision Score : 1.0
Recall Score : 0.8125
F1 Score : 0.896551724137931
Confusion Matrix : 
[[14  0]
 [ 3 13]]
Accuracy Score : 0.8666666666666667
Precision Score : 0.8666666666666667
Recall Score : 0.8666666666666667
F1 Score : 0.8666666666666667
Confusion Matrix : 
[[13  2]
 [ 2 13]]
Accuracy Score : 0.6333333333333333
Precision Score : 0.7058823529411765
Recall Score : 0.6666666666666666
F1 Score : 0.6857142857142857
Confusion Matrix : 
[[ 7  5]
 [ 6 12]]
Accuracy Score : 0.8666666666666667
Precision Score : 0.9166666666666666
Recall Score : 0.7857142857142857
F1 Score : 0.8461538461538461
Confusion Matrix : 
[[15  1]
 [ 3 11]]
Accuracy Score : 0.8333333333333334
Precision Score : 0.75
Recall Score : 0.6666666666666666
F1 Score : 0.7058823529411765
Confusion Matrix : 
[[19  2]
 [ 3  6]]
Accuracy Score : 0.8666666666666667
Precision Score : 0.8947368421052632
Recall Score : 0.8947368421052632
F1 Score : 0.8947368421052632
Confusion Matrix : 
[[ 9  2]
 [ 2 17]]
A

In [21]:

from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.svm import SVC



from sklearn import metrics
from sklearn.model_selection import KFold
KFold
# prepare cross validation
kfold = KFold(n_splits=10, random_state=123, shuffle=True)

# enumerate splits on the features (X) set 
for train_indx, test_indx in kfold.split(X):    
    X_train = X.iloc[train_indx]                  # -- set of X_train from X-set
    X_test  = X.iloc[test_indx]                   # -- set of X_test from X-set
    y_train, y_test = y.iloc[train_indx], y.iloc[test_indx] # -- set of y_train, y_test from y-set
    
    # Apply these set as a regular process for any classifier to test
    clf = SVC(kernel = 'rbf').fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    
    # Model Evaluation metrics 
    print('Accuracy Score : '  + str(accuracy_score(y_test,y_pred)))
    print('Precision Score : ' + str(precision_score(y_test,y_pred, pos_label='1')))
    print('Recall Score : '    + str(recall_score(y_test,y_pred, pos_label='1')))
    print('F1 Score : '        + str(f1_score(y_test,y_pred, pos_label='1')))

    #Logistic Regression Classifier Confusion matrix
    print('Confusion Matrix : \n' + str(confusion_matrix(y_test,y_pred)))
    
    conf = confusion_matrix(y_test, y_pred)

TP = conf[0,0]
FP = conf[0,1]
TN = conf[1,0]
FN = conf[1,1]

sensitivity = TP / float(FN + TP)

print(' sensitivity : \n' + str(sensitivity))

specificity = TN / (TN + FP)

print(' specificity : \n' + str(specificity))

Accuracy Score : 0.9
Precision Score : 0.9333333333333333
Recall Score : 0.875
F1 Score : 0.9032258064516129
Confusion Matrix : 
[[13  1]
 [ 2 14]]
Accuracy Score : 0.8333333333333334
Precision Score : 0.8125
Recall Score : 0.8666666666666667
F1 Score : 0.8387096774193549
Confusion Matrix : 
[[12  3]
 [ 2 13]]
Accuracy Score : 0.7
Precision Score : 0.8
Recall Score : 0.6666666666666666
F1 Score : 0.7272727272727272
Confusion Matrix : 
[[ 9  3]
 [ 6 12]]
Accuracy Score : 0.8666666666666667
Precision Score : 0.8571428571428571
Recall Score : 0.8571428571428571
F1 Score : 0.8571428571428571
Confusion Matrix : 
[[14  2]
 [ 2 12]]
Accuracy Score : 0.8
Precision Score : 0.6666666666666666
Recall Score : 0.6666666666666666
F1 Score : 0.6666666666666666
Confusion Matrix : 
[[18  3]
 [ 3  6]]
Accuracy Score : 0.8
Precision Score : 0.8823529411764706
Recall Score : 0.7894736842105263
F1 Score : 0.8333333333333333
Confusion Matrix : 
[[ 9  2]
 [ 4 15]]
Accuracy Score : 0.9310344827586207
Precisio